# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!
#本文件是通过qt designer 和 pyuic生成的

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Weather(object):
    def setupUi(self, Weather):
        Weather.setObjectName("Weather")
        Weather.resize(1254, 733)
        self.widget = QtWidgets.QWidget(Weather)
        self.widget.setGeometry(QtCore.QRect(40, 410, 151, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.lon = QtWidgets.QLineEdit(self.widget)
        self.lon.setObjectName("lon")
        self.verticalLayout_2.addWidget(self.lon)
        self.lat = QtWidgets.QLineEdit(self.widget)
        self.lat.setObjectName("lat")
        self.verticalLayout_2.addWidget(self.lat)
        self.GPSSer = QtWidgets.QPushButton(self.widget)
        self.GPSSer.setObjectName("GPSSer")
        self.verticalLayout_2.addWidget(self.GPSSer)
        self.widget1 = QtWidgets.QWidget(Weather)
        self.widget1.setGeometry(QtCore.QRect(41, 141, 151, 107))
        self.widget1.setObjectName("widget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.CityName = QtWidgets.QLineEdit(self.widget1)
        self.CityName.setObjectName("CityName")
        self.verticalLayout.addWidget(self.CityName)
        self.CitySer = QtWidgets.QPushButton(self.widget1)
        self.CitySer.setObjectName("CitySer")
        self.verticalLayout.addWidget(self.CitySer)
        self.widget2 = QtWidgets.QWidget(Weather)
        self.widget2.setGeometry(QtCore.QRect(240, 50, 951, 612))
        self.widget2.setObjectName("widget2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem, 0, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem2, 2, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_17 = QtWidgets.QLabel(self.widget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 4, 0, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 2, 0, 1, 1)
        self.travelindex = QtWidgets.QLineEdit(self.widget2)
        self.travelindex.setObjectName("travelindex")
        self.gridLayout_3.addWidget(self.travelindex, 4, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 5, 0, 1, 1)
        self.exindex = QtWidgets.QLineEdit(self.widget2)
        self.exindex.setObjectName("exindex")
        self.gridLayout_3.addWidget(self.exindex, 5, 1, 1, 1)
        self.uvindex = QtWidgets.QLineEdit(self.widget2)
        self.uvindex.setObjectName("uvindex")
        self.gridLayout_3.addWidget(self.uvindex, 2, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 3, 0, 1, 1)
        self.washindex = QtWidgets.QLineEdit(self.widget2)
        self.washindex.setObjectName("washindex")
        self.gridLayout_3.addWidget(self.washindex, 3, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 6, 0, 1, 1)
        self.dress_ad = QtWidgets.QTextEdit(self.widget2)
        self.dress_ad.setObjectName("dress_ad")
        self.gridLayout_3.addWidget(self.dress_ad, 6, 1, 1, 1)
        self.dressindex = QtWidgets.QLineEdit(self.widget2)
        self.dressindex.setObjectName("dressindex")
        self.gridLayout_3.addWidget(self.dressindex, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 0, 3, 2, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_24 = QtWidgets.QLabel(self.widget2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_6.addWidget(self.label_24, 2, 0, 1, 1)
        self.AQI = QtWidgets.QLineEdit(self.widget2)
        self.AQI.setObjectName("AQI")
        self.gridLayout_6.addWidget(self.AQI, 2, 1, 1, 1)
        self.PM25 = QtWidgets.QLineEdit(self.widget2)
        self.PM25.setObjectName("PM25")
        self.gridLayout_6.addWidget(self.PM25, 1, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 0, 0, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_6.addWidget(self.label_23, 1, 0, 1, 1)
        self.PM10 = QtWidgets.QLineEdit(self.widget2)
        self.PM10.setObjectName("PM10")
        self.gridLayout_6.addWidget(self.PM10, 4, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_6.addWidget(self.label_27, 5, 0, 1, 1)
        self.NO2 = QtWidgets.QLineEdit(self.widget2)
        self.NO2.setObjectName("NO2")
        self.gridLayout_6.addWidget(self.NO2, 6, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_6.addWidget(self.label_26, 4, 0, 1, 1)
        self.QUA = QtWidgets.QLineEdit(self.widget2)
        self.QUA.setObjectName("QUA")
        self.gridLayout_6.addWidget(self.QUA, 3, 1, 1, 1)
        self.CO = QtWidgets.QLineEdit(self.widget2)
        self.CO.setObjectName("CO")
        self.gridLayout_6.addWidget(self.CO, 5, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget2)
        self.label_25.setObjectName("label_25")
        self.gridLayout_6.addWidget(self.label_25, 3, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_6.addWidget(self.label_28, 6, 0, 1, 1)
        self.SO2 = QtWidgets.QLineEdit(self.widget2)
        self.SO2.setObjectName("SO2")
        self.gridLayout_6.addWidget(self.SO2, 8, 1, 1, 1)
        self.O3 = QtWidgets.QLineEdit(self.widget2)
        self.O3.setObjectName("O3")
        self.gridLayout_6.addWidget(self.O3, 7, 1, 1, 1)
        self.time = QtWidgets.QTextEdit(self.widget2)
        self.time.setObjectName("time")
        self.gridLayout_6.addWidget(self.time, 9, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_6.addWidget(self.label_29, 7, 0, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_6.addWidget(self.label_30, 8, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_6.addWidget(self.label_31, 9, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 5, 2, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 2)
        self.todtemp = QtWidgets.QLineEdit(self.widget2)
        self.todtemp.setObjectName("todtemp")
        self.gridLayout_2.addWidget(self.todtemp, 2, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.todw = QtWidgets.QLineEdit(self.widget2)
        self.todw.setObjectName("todw")
        self.gridLayout_2.addWidget(self.todw, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.todwd = QtWidgets.QLineEdit(self.widget2)
        self.todwd.setObjectName("todwd")
        self.gridLayout_2.addWidget(self.todwd, 4, 1, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.sktemp = QtWidgets.QLineEdit(self.widget2)
        self.sktemp.setObjectName("sktemp")
        self.gridLayout.addWidget(self.sktemp, 1, 1, 1, 1)
        self.skwd = QtWidgets.QLineEdit(self.widget2)
        self.skwd.setObjectName("skwd")
        self.gridLayout.addWidget(self.skwd, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.skwf = QtWidgets.QLineEdit(self.widget2)
        self.skwf.setObjectName("skwf")
        self.gridLayout.addWidget(self.skwf, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 3, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 4, 0, 1, 1)
        self.skhum = QtWidgets.QLineEdit(self.widget2)
        self.skhum.setObjectName("skhum")
        self.gridLayout.addWidget(self.skhum, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.date4w = QtWidgets.QLineEdit(self.widget2)
        self.date4w.setObjectName("date4w")
        self.gridLayout_4.addWidget(self.date4w, 2, 4, 1, 1)
        self.date4t = QtWidgets.QLineEdit(self.widget2)
        self.date4t.setObjectName("date4t")
        self.gridLayout_4.addWidget(self.date4t, 1, 4, 1, 1)
        self.date3w = QtWidgets.QLineEdit(self.widget2)
        self.date3w.setObjectName("date3w")
        self.gridLayout_4.addWidget(self.date3w, 2, 3, 1, 1)
        self.date6w = QtWidgets.QLineEdit(self.widget2)
        self.date6w.setObjectName("date6w")
        self.gridLayout_4.addWidget(self.date6w, 2, 6, 1, 1)
        self.date3t = QtWidgets.QLineEdit(self.widget2)
        self.date3t.setObjectName("date3t")
        self.gridLayout_4.addWidget(self.date3t, 1, 3, 1, 1)
        self.date2 = QtWidgets.QLineEdit(self.widget2)
        self.date2.setObjectName("date2")
        self.gridLayout_4.addWidget(self.date2, 0, 2, 1, 1)
        self.date4 = QtWidgets.QLineEdit(self.widget2)
        self.date4.setObjectName("date4")
        self.gridLayout_4.addWidget(self.date4, 0, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget2)
        font = QtGui.QFont()
        font.setFamily("3ds")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_19.setAutoFillBackground(False)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.date1 = QtWidgets.QLineEdit(self.widget2)
        self.date1.setObjectName("date1")
        self.gridLayout_4.addWidget(self.date1, 0, 1, 1, 1)
        self.date3 = QtWidgets.QLineEdit(self.widget2)
        self.date3.setObjectName("date3")
        self.gridLayout_4.addWidget(self.date3, 0, 3, 1, 1)
        self.date6 = QtWidgets.QLineEdit(self.widget2)
        self.date6.setObjectName("date6")
        self.gridLayout_4.addWidget(self.date6, 0, 6, 1, 1)
        self.date7 = QtWidgets.QLineEdit(self.widget2)
        self.date7.setObjectName("date7")
        self.gridLayout_4.addWidget(self.date7, 0, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_4.addWidget(self.label_20, 1, 0, 1, 1)
        self.date5 = QtWidgets.QLineEdit(self.widget2)
        self.date5.setObjectName("date5")
        self.gridLayout_4.addWidget(self.date5, 0, 5, 1, 1)
        self.date7t = QtWidgets.QLineEdit(self.widget2)
        self.date7t.setObjectName("date7t")
        self.gridLayout_4.addWidget(self.date7t, 1, 7, 1, 1)
        self.date7w = QtWidgets.QLineEdit(self.widget2)
        self.date7w.setObjectName("date7w")
        self.gridLayout_4.addWidget(self.date7w, 2, 7, 1, 1)
        self.date1w = QtWidgets.QLineEdit(self.widget2)
        self.date1w.setObjectName("date1w")
        self.gridLayout_4.addWidget(self.date1w, 2, 1, 1, 1)
        self.date2w = QtWidgets.QLineEdit(self.widget2)
        self.date2w.setObjectName("date2w")
        self.gridLayout_4.addWidget(self.date2w, 2, 2, 1, 1)
        self.date2t = QtWidgets.QLineEdit(self.widget2)
        self.date2t.setObjectName("date2t")
        self.gridLayout_4.addWidget(self.date2t, 1, 2, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_4.addWidget(self.label_21, 2, 0, 1, 1)
        self.date1t = QtWidgets.QLineEdit(self.widget2)
        self.date1t.setObjectName("date1t")
        self.gridLayout_4.addWidget(self.date1t, 1, 1, 1, 1)
        self.date6t = QtWidgets.QLineEdit(self.widget2)
        self.date6t.setObjectName("date6t")
        self.gridLayout_4.addWidget(self.date6t, 1, 6, 1, 1)
        self.date5w = QtWidgets.QLineEdit(self.widget2)
        self.date5w.setObjectName("date5w")
        self.gridLayout_4.addWidget(self.date5w, 2, 5, 1, 1)
        self.date5t = QtWidgets.QLineEdit(self.widget2)
        self.date5t.setObjectName("date5t")
        self.gridLayout_4.addWidget(self.date5t, 1, 5, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 3, 0, 1, 6)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_5.addItem(spacerItem4, 0, 1, 1, 1)
        self.label_2.raise_()
        self.label_3.raise_()
        self.lat.raise_()
        self.GPSSer.raise_()
        self.CityName.raise_()
        self.CitySer.raise_()
        self.lon.raise_()
        self.label_11.raise_()
        self.dress_ad.raise_()
        self.label_3.raise_()

        self.retranslateUi(Weather)
        self.CitySer.clicked.connect(Weather.push_butn_city)
        self.GPSSer.clicked.connect(Weather.push_butn_gps)
        QtCore.QMetaObject.connectSlotsByName(Weather)

    def retranslateUi(self, Weather):
        _translate = QtCore.QCoreApplication.translate
        Weather.setWindowTitle(_translate("Weather", "Form"))
        self.label_3.setText(_translate("Weather", "GPS定位查询"))
        self.lon.setText(_translate("Weather", "请输入经度"))
        self.lat.setText(_translate("Weather", "请输入纬度"))
        self.GPSSer.setText(_translate("Weather", "查询"))
        self.label_2.setText(_translate("Weather", "城市名查询"))
        self.CityName.setText(_translate("Weather", "请输入城市"))
        self.CitySer.setText(_translate("Weather", "查询"))
        self.label_17.setText(_translate("Weather", "旅游指数"))
        self.label_15.setText(_translate("Weather", "紫外线强度"))
        self.label_18.setText(_translate("Weather", "晨练指数"))
        self.label_13.setText(_translate("Weather", "生活指数"))
        self.label_16.setText(_translate("Weather", "洗车指数"))
        self.label_11.setText(_translate("Weather", "穿衣建议"))
        self.label_14.setText(_translate("Weather", "穿衣指数"))
        self.label_24.setText(_translate("Weather", "AQI"))
        self.label_22.setText(_translate("Weather", "空气质量"))
        self.label_23.setText(_translate("Weather", "PM2.5"))
        self.label_27.setText(_translate("Weather", "CO"))
        self.label_26.setText(_translate("Weather", "PM10"))
        self.label_25.setText(_translate("Weather", "quality"))
        self.label_28.setText(_translate("Weather", "NO2"))
        self.label_29.setText(_translate("Weather", "O3"))
        self.label_30.setText(_translate("Weather", "SO2"))
        self.label_31.setText(_translate("Weather", "更新时间"))
        self.label_12.setText(_translate("Weather", "风向"))
        self.label_8.setText(_translate("Weather", "今日天气"))
        self.label_9.setText(_translate("Weather", "温度"))
        self.label_10.setText(_translate("Weather", "天气"))
        self.label_4.setText(_translate("Weather", "温度"))
        self.label_5.setText(_translate("Weather", "湿度"))
        self.label_6.setText(_translate("Weather", "风向"))
        self.label_7.setText(_translate("Weather", "风力"))
        self.label.setText(_translate("Weather", " 实况天气"))
        self.label_19.setText(_translate("Weather", "未来天气"))
        self.label_20.setText(_translate("Weather", "温度"))
        self.label_21.setText(_translate("Weather", "天气"))

